image: python:2.7

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - .venv/

before_script:
  - python -V
  - pip install virtualenv
  - virtualenv .venv
  - source .venv/bin/activate
  - pip install tox

test:
  stage: test
  tags:
  - docker
  - forge
  - shared
  script:
  - tox -e pep8,py27,functional

pages:
  stage: deploy
  tags:
  - docker
  - forge
  - shared
  script:
  - tox -e docs
  - mv doc/build/html public
  artifacts:
    paths:
    - public
  only:
  - master
